# Theme Settings
markdown                 : kramdown
remote_theme             : mmistakes/minimal-mistakes
minimal_mistakes_skin    : "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale                   : "en-US"
title                    : "ReCompute"
description              : "Harvard Responsible Computing Collective"
url                      : "https://harvard-recompute.github.io"
repository               : "harvard-recompute"
logo                     : # path of logo image to display in the masthead, e.g. "/assets/images/88x88.png"
atom_feed:
  path                   : # blank (default) uses feed.xml
  hide                   : true

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-remote-theme

# Read Files
include: 
  - _pages

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules

defaults:
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: false